---
title: "esm204_hw4"
author: "Nicole Schmidt"
date: "5/22/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyr)
library(dplyr)
library(ggplot2)
```


```{r}

TTtmp = 4.4 
beta = .05
g = .01
eta = 0.5
delta = .005
r = delta + eta*g 

tauf = function(t, TT)
{
  out = min(t*TT/100, TT)
  return(out)
}

econ = function(temp)
{
  out = exp(-beta*temp^2)
  return(out)
}

consumption = function(t, temp)
{
  out = econ(temp)*exp(g*t)
  return(out)
}

utility = function(C)
{
  out = (C^(1 - eta))/ (1 - eta)
              return(out)
}

TT = 0
DF_no_change = data.frame(t=seq(1,200)) %>% 
  rowwise() %>% 
  mutate(tau = tauf(t,TT)) %>% 
  mutate(K = econ(tau)) %>% 
  mutate(C = consumption(t, tau)) %>% 
  mutate(U = utility(C)) %>% 
  mutate(PVU = U/(1+r)^t)
  NPV = sum(DF$PVU)

```

Plots 

```{r}
##a) plot of temp v time for no climate change (T=0)
TT_nc = 0
DF_nc = data.frame(t=seq(1,200)) %>% 
  rowwise() %>% 
  mutate(tau = tauf(t,TT_nc)) %>% 
  mutate(K = econ(tau)) %>% 
  mutate(C = consumption(t, tau)) %>% 
  mutate(U = utility(C)) %>% 
  mutate(PVU = U/(1+r)^t)
  NPV_nc = sum(DF$PVU)
  
  TT_moderate = 2
DF_moderate = data.frame(t=seq(1,200)) %>% 
  rowwise() %>% 
  mutate(tau = tauf(t,TT_moderate)) %>% 
  mutate(K = econ(tau)) %>% 
  mutate(C = consumption(t, tau)) %>% 
  mutate(U = utility(C)) %>% 
  mutate(PVU = U/(1+r)^t)
  NPV_moderate = sum(DF$PVU)
  
  
  TT_extreme = 8
DF_extreme = data.frame(t=seq(1,200)) %>% 
  rowwise() %>% 
  mutate(tau = tauf(t,TT_extreme)) %>% 
  mutate(K = econ(tau)) %>% 
  mutate(C = consumption(t, tau)) %>% 
  mutate(U = utility(C)) %>% 
  mutate(PVU = U/(1+r)^t)
  NPV_extreme = sum(DF$PVU)

  
  ggplot()+
    geom_line(data = DF_nc, aes(x = t,
                                y = tau),
              color = "blue") +
    geom_line(data = DF_moderate, aes(x = t,
                                      y = tau),
              color = "orange")+
    geom_line(data = DF_extreme, aes(x = t,
                                      y = tau),
              color = "red") + 
    theme_minimal()
    

```

```{r}
##B consumption over time 
 ggplot()+
    geom_line(data = DF_nc, aes(x = t,
                                y = C),
                                color = "blue") +
    geom_line(data = DF_moderate, aes(x = t,
                                      y = C),
                                      color = "orange")+
    geom_line(data = DF_extreme, aes(x = t,
                                      y = C),
                                     color = "red") + 
    theme_minimal()

```


```{r}
##C Utility over time 
 ggplot()+
    geom_line(data = DF_nc, aes(x = t,
                                y = U),
                                color = "blue") +
    geom_line(data = DF_moderate, aes(x = t,
                                      y = U),
                                      color = "orange")+
    geom_line(data = DF_extreme, aes(x = t,
                                      y = U),
                                     color = "red") + 
    theme_minimal()
```

### Business as Usual
```{r}

t <- c(1:200)

temp_overtime <- function(t,T){
  temp <- out(t,T)
   <- 0.5*(alpha - p)*q
  return(out)
}

temp = function(t,T) # Name the function than Tell the function what the inputs are
{ 
out = min(t*T/100,T)
return(out)
}

#df=data.frame(ID=(1:10),Value=(value)) 
 # assign("df",df,envir = .GlobalEnv)
  #View(df)

df <- data.frame(t = (1:200),T = , row.names=NULL) # creating the data frame

no_change <- temp(T=0, t=c(1:200)) #defining the variables
modest_change <- temp(T=2, t=c(1:200))
extreme_change <- temp(T=8, t=c(1:200))

#temp(t=50, T=5) # calling the function; defining the variables
#temp (t = 50, T = 10) # different values 
#temp(t = 1, T = 1000)
```

### Hotter Senario; Economic Activity. K(t) is the fraction of economic activity that is retained in a year if the temperature is r(t) 

```{r}
beta <- 0.05
econ = function(r,t) #name function and inputs
  
out = exp(-beta*r(t)^2) # write out equation

econ(r= , t= )

```


#### Economic activity (Consumption) grows over time rate g, reduced by k: Total consumption at time t:
```{r}

econ = function(r,t) #name function and inputs
out = exp(-beta*r(t)^2) # write out equation

consumption = function(out*exp(g*t))

```

Societies Utility from consumption:
```{r}

n<- .5

utility = function(C,n)
  
out= (C^(1-n))/(1-n)


```

